name: 'Zoocha Security Recipe'
description: 'Provides security modules with baseline configuration'
type: 'Feature'

install:
  - seckit
  - password_policy
  - password_policy_characters
  - password_policy_history
  - password_policy_length
  - username_enumeration_prevention
  - flood_control

config:
  # Allow config import to continue if config already exists.
  strict: false
  import:
    # Import all of Admin Toolbar's modules config.
    seckit: '*'
    password_policy: '*'
    username_enumeration_prevention: '*'
    flood_control: '*'
  actions:
      user.flood:
        simple_config_update:
          user_limit: 10
