name: 'Zoocha Security Recipe'
description: 'Provides security modules with baseline configuration'
type: 'Feature'

recipe:
  - zr-security-username
  - zr-security-autologout
  - zr-security-floodcontrol
  - zr-security-seckit
  - zr-security-password-policy
  - zr-security-clamav

config:
  # Allow config import to continue if config already exists.
  strict: false
  actions:
      user.flood:
        simple_config_update:
          user_limit: 10
