name: 'Zoocha Security Recipe'
description: 'Provides security modules with baseline configuration'
type: 'Feature'

install:
  - zr-security-username
  - zr-security-autologout
  - zr-security-floodcontrol
  - zr-security-seckit
  - zr-security-password-policy
  - zr-security-clamav

config:
  # Allow config import to continue if config already exists.
  strict: false
  import:
    # Import all of Admin Toolbar's modules config.
    seckit: '*'
    password_policy: '*'
    username_enumeration_prevention: '*'
    flood_control: '*'
  actions:
      user.flood:
        simple_config_update:
          user_limit: 10
